server:
  port: 8085

spring:
  application:
    name: ms-ai-fleet-allocation

  datasource:
    url: jdbc:postgresql://localhost:5432/truckdar_db
    username: truckdar_admin
    password: truckdar_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fleet-allocation-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

services:
  load-allocation:
    url: http://localhost:8083
  fleets-drivers:
    url: http://localhost:8081